schema: 'schema.gql'
documents: 'apps/prunk/**/*.gql'
extensions:
  codegen:
    generates:
      apps/prunk/src/@generated/generated.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-apollo-angular
        config:
          addExplicitOverride: true
