# Downgraded to 3.7 to ensure it works with non-docker desktop
version: '3.7'

services:
  postgres:
    container_name: postgres_runk
    # Per Ron, he's okay with using the versions of postgres off the docker hub, it's more updated.
    # the version from iron bank is literally 3 semvar versions behind (that's a lot!)
    # image: registry1.dso.mil/ironbank/opensource/postgres/postgresql12:latest
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD

volumes:
  postgres-vol:
