mutation upsertPersonPR($create: PersonCreateInput!, $update: PersonUpdateInput!, $where: PersonWhereUniqueInput!) {
  upsertPerson(create: $create, update: $update, where: $where) {
    id
    firstName
  }
}

mutation upsertOrgPR($create: OrgCreateInput!, $update: OrgUpdateInput!, $where: OrgWhereUniqueInput!) {
  upsertOrg(create: $create, update: $update, where: $where) {
    name
  }
}
